version: '3.7'
services:
  traccar:
    image: "traccar/traccar:latest"
    environment:
      VIRTUAL_HOST: traccar.wildsong.biz
      VIRTUAL_PORT: 8082
      LETSENCRYPT_HOST: traccar.wildsong.biz
      LETSENCRYPT_MAIL: brian@wildsong.biz
    volumes:
      - ./traccar_h2.xml:/opt/traccar/conf/traccar.xml
      - logs:/opt/traccar/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8082:8082"
      - "5055:5055"     # cellphones
      - "5055:5055/udp" # cellphones
    networks:
      - proxy_net
    deploy:
      mode: global
      update_config:
        order: 'stop-first'
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  logs:
    name: traccar_logs

networks:
  proxy_net:
    name: proxy_net
    external: true
    