version: '3.6'
services:
  traccar:
    depends_on:
      - mysql
    image: "traccar/traccar:latest"
    env_file: traccar.env
    volumes:
      - traccar_conf:/opt/traccar/conf
      - traccar_logs:/opt/traccar/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8082:8082"
      - "5055:5055"     # cellphones
      - "5055:5055/udp" # cellphones
    networks:
      - traccar_net
    deploy:
      replicas: 1
      update_config:
        order: 'stop-first'

  # Only traccar needs to see port 3306 and
  # that's visible already on traccar_net
  # so I don't need 'ports' or 'expose'
  # 
  # NB Hostname for traccar service will be "mysql". (Sort of painfully obvious now.)
  mysql:
    image: "mysql:5.6.30"
    env_file: mysql.env
    volumes:
      - traccar_database:/var/lib/mysql
    networks:
      - traccar_net
    deploy:
      replicas: 1
      update_config:
        order: 'stop-first'

volumes:
  traccar_conf:
    name: traccar_conf
  traccar_logs:
    name: traccar_logs
  traccar_database:
    name: traccar_database

networks:
  traccar_net:
    external: true
